//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gsEntities : DbContext
    {
        public gsEntities()
            : base("name=gsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<arquivos> arquivos { get; set; }
        public DbSet<categorias> categorias { get; set; }
        public DbSet<itens_pedido> itens_pedido { get; set; }
        public DbSet<oculos> oculos { get; set; }
        public DbSet<oculos_armacoes> oculos_armacoes { get; set; }
        public DbSet<oculos_estilos> oculos_estilos { get; set; }
        public DbSet<oculos_lentes> oculos_lentes { get; set; }
        public DbSet<pedidos> pedidos { get; set; }
        public DbSet<marcas> marcas { get; set; }
        public DbSet<formatos> formatos { get; set; }
        public DbSet<clientes> clientes { get; set; }
    }
}
