//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class itens_pedido
    {
        public int id { get; set; }
        public int oculos_id { get; set; }
        public decimal preco { get; set; }
        public int quantidade { get; set; }
        public int pedido_id { get; set; }
    
        public virtual oculos oculos { get; set; }
        public virtual pedidos pedidos { get; set; }
    }
}
