//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oculos
    {
        public oculos()
        {
            this.itens_pedido = new HashSet<itens_pedido>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string slug { get; set; }
        public Nullable<System.DateTime> data_criacao { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public Nullable<int> ordem { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<decimal> preco { get; set; }
        public string descricao { get; set; }
        public string caracteristicas { get; set; }
        public string medidas { get; set; }
        public Nullable<decimal> preco_desconto { get; set; }
        public string modelo { get; set; }
        public Nullable<int> masculino { get; set; }
        public Nullable<int> feminino { get; set; }
        public Nullable<int> infantil { get; set; }
        public Nullable<int> marca { get; set; }
    
        public virtual ICollection<itens_pedido> itens_pedido { get; set; }
    }
}
